# Generated by Django 4.1.5 on 2023-01-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_rename_dname_branch_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='bankapp.district'),
        ),
    ]
